### ISSUE TITLE
Service catalog not showing up with example openshift-ansible inventory

### ISSUE THREAD

**Issue by dougbtv** [redhat-nfvpe/base-infra-bootstrap#20]
Frank has reported that during his cluster deployment, he doesn't have a service catalog.

This includes with the inclusion of the variable set as such:

```
openshift_enable_service_catalog=true
```

Need to circle back around and see how to make sure that gets spun up. Haven't looked at this since some work trying to get APBs up and running and definitely ran into some issues at that time.

**Comment by dougbtv** [comment]
example inventory in [pastebin here](http://pastebin.test.redhat.com/554186)

**Comment by leifmadsen** [comment]
Of note, I've added an example that adds persistent storage, and this will be required by a number of the playbooks to make this work.

Additionally, you can't really spin up NFS (which is basically required for ASB) on Atomic, so I have a task open that will add the ability to control the type of OS installed for a node, so that we can create an NFS machine to satisfy that dependency. That way we *should* be able to spin up infra that can support all the service catalogs.

**Comment by leifmadsen** [comment]
There are examples that allow for the catalog to be created now.
